import { Bell, FileUp, ReceiptText, UserPlus, UsersRound } from "lucide-react";
import { useState, type FormEvent } from "react";
import { currency, dateLabel, EmptyState, Field, Modal, PageHeading, StatusPill, SubmitButton } from "./components";
import type { BootstrapPayload, PayRequest, PortalUser } from "./types";
import type { Mutation } from "./AdminPages";

const payTone = (status: string) => status === "paid" || status === "approved" ? "green" : status === "rejected" ? "red" : status === "needs_revision" ? "orange" : "cyan";

export function AdminUsers({ data, mutate }: { data: BootstrapPayload; mutate: Mutation }) {
  const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); try { await mutate("/api/users", "POST", { role: form.get("role"), name: form.get("name"), email: form.get("email"), phone: form.get("phone"), company: form.get("company"), trade: form.get("trade"), projectIds: form.getAll("projectIds") }); setOpen(false); } finally { setBusy(false); } };
  return <><PageHeading eyebrow="Full access control" title="User management" detail="Create unlimited Admin, Client, and Subcontractor accounts. New accounts receive a one-time temporary password and must change it at first login." actions={<button className="button button-primary" onClick={() => setOpen(true)}><UserPlus size={16}/> Add user</button>} /><section className="panel"><div className="table-wrap"><table><thead><tr><th>User</th><th>Role</th><th>Contact</th><th>Access</th><th>Last sign in</th><th>Status</th><th /></tr></thead><tbody>{(data.users || []).map((user) => <tr key={user.id}><td><strong>{user.name}</strong><small>{user.company || "—"}</small></td><td><StatusPill tone="cyan">{user.role}</StatusPill></td><td>{user.email}<small>{user.phone || "No phone"}</small></td><td>{user.role === "admin" ? "All projects" : `${user.projectIds.length} project(s), ${user.jobIds.length} job(s)`}</td><td>{user.lastLoginAt ? dateLabel(user.lastLoginAt) : "Never"}</td><td><StatusPill tone={user.active ? "green" : "red"}>{user.active ? "Active" : "Disabled"}</StatusPill></td><td><button className="text-button" onClick={() => void mutate(`/api/users/${user.id}/reset-password`, "POST")}>Reset password</button><button className="text-button" onClick={() => void mutate(`/api/users/${user.id}`, "PATCH", { active: !user.active })}>{user.active ? "Disable" : "Reactivate"}</button></td></tr>)}</tbody></table></div></section>{open && <Modal title="Create user" eyebrow="Temporary password: SteelCool123" onClose={() => setOpen(false)}><form className="form-grid" onSubmit={submit}><Field label="Role"><select name="role"><option value="client">Client</option><option value="subcontractor">Subcontractor</option><option value="admin">Admin</option></select></Field><Field label="Full name"><input name="name" required /></Field><Field label="Email / login"><input name="email" type="email" required /></Field><Field label="Phone"><input name="phone" /></Field><Field label="Company"><input name="company" /></Field><Field label="Trade"><input name="trade" /></Field><Field label="Project access"><select name="projectIds" multiple>{data.projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></Field><div className="form-actions"><button className="button button-ghost" type="button" onClick={() => setOpen(false)}>Cancel</button><SubmitButton busy={busy}>Create user</SubmitButton></div></form></Modal>}</>;
}

export function AdminPayRequests({ data, mutate }: { data: BootstrapPayload; mutate: Mutation }) {
  const [selected, setSelected] = useState<PayRequest | null>(null); const [busy, setBusy] = useState(false); const requests = data.payRequests || [];
  const update = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!selected) return; const f = new FormData(event.currentTarget); setBusy(true); try { await mutate(`/api/pay-requests/${selected.id}`, "PATCH", { status: f.get("status"), approvedAmount: f.get("approvedAmount") || undefined, adminNotes: f.get("adminNotes"), paymentDate: f.get("paymentDate") || undefined, paymentReference: f.get("paymentReference") }); setSelected(null); } finally { setBusy(false); } };
  return <><PageHeading eyebrow="Payment workflow" title={`Invoices / pay requests${requests.filter((item) => !item.readByAdmin).length ? ` (${requests.filter((item) => !item.readByAdmin).length})` : ""}`} detail="Review invoice-backed requests, record decisions, and retain a complete activity trail." /><section className="panel"><div className="table-wrap"><table><thead><tr><th>Invoice</th><th>Subcontractor</th><th>Project / job</th><th>Requested</th><th>Status</th><th /></tr></thead><tbody>{requests.map((item) => <tr key={item.id}><td><strong>{item.invoiceNumber}</strong><small>{dateLabel(item.invoiceDate)}</small></td><td>{item.company || item.subcontractorName}</td><td>{data.projects.find((project) => project.id === item.projectId)?.name}<small>{data.jobs.find((job) => job.id === item.jobId)?.title}</small></td><td>{currency.format(item.amountRequested)}</td><td><StatusPill tone={payTone(item.status)}>{item.status.replaceAll("_", " ")}</StatusPill></td><td><button className="button button-small" onClick={() => setSelected(item)}>Review</button></td></tr>)}</tbody></table></div>{!requests.length && <EmptyState title="No pay requests" detail="Invoice-backed subcontractor requests will arrive here." />}</section>{selected && <Modal title={`Review ${selected.invoiceNumber}`} eyebrow={selected.company} onClose={() => setSelected(null)}><form className="form-grid" onSubmit={update}><div className="callout"><ReceiptText /><span><strong>{currency.format(selected.amountRequested)} requested</strong><small>{selected.description || "No description provided"}</small></span></div><Field label="Status"><select name="status" defaultValue={selected.status}>{["under_review","approved","partially_approved","payment_processing","paid","rejected","needs_revision"].map((status) => <option key={status}>{status.replaceAll("_", " ")}</option>)}</select></Field><Field label="Approved amount"><input name="approvedAmount" type="number" min="0" defaultValue={selected.approvedAmount} /></Field><Field label="Payment date"><input name="paymentDate" type="date" defaultValue={selected.paymentDate} /></Field><Field label="Check / reference number"><input name="paymentReference" defaultValue={selected.paymentReference} /></Field><Field label="Admin notes"><textarea name="adminNotes" rows={4} defaultValue={selected.adminNotes} /></Field><div className="form-actions"><button type="button" className="button button-ghost" onClick={() => setSelected(null)}>Cancel</button><SubmitButton busy={busy}>Save decision</SubmitButton></div></form></Modal>}</>;
}

async function encode(file: File) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(",")[1] || ""); reader.onerror = reject; reader.readAsDataURL(file); }); }
export function SubPayRequests({ data, mutate }: { data: BootstrapPayload; mutate: Mutation }) {
  const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const jobs = data.jobs.filter((job) => job.contractorId === data.viewer.id);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const f = new FormData(event.currentTarget); const invoice = f.get("invoice") as File; if (!invoice?.size) return; const job = data.jobs.find((item) => item.id === f.get("jobId")); if (!job) return; setBusy(true); try { await mutate("/api/pay-requests", "POST", { projectId: job.projectId, jobId: job.id, amountRequested: f.get("amountRequested"), invoiceNumber: f.get("invoiceNumber"), invoiceDate: f.get("invoiceDate"), description: f.get("description"), invoice: { name: invoice.name, mimeType: invoice.type, contentBase64: await encode(invoice) }, attachments: [] }); setOpen(false); } finally { setBusy(false); } };
  return <><PageHeading eyebrow="Invoice-backed requests" title="Pay requests" detail="Submit payment requests only for your assigned jobs. An invoice upload is required." actions={<button className="button button-primary" onClick={() => setOpen(true)}><ReceiptText size={16}/> New pay request</button>} /><div className="assigned-grid">{(data.payRequests || []).map((item) => <article className="assigned-card" key={item.id}><header><StatusPill tone={payTone(item.status)}>{item.status.replaceAll("_", " ")}</StatusPill><span>{item.invoiceNumber}</span></header><h2>{currency.format(item.amountRequested)}</h2><p>{data.jobs.find((job) => job.id === item.jobId)?.title}</p><div className="assigned-facts"><span><small>Submitted</small><strong>{dateLabel(item.createdAt)}</strong></span><span><small>Approved</small><strong>{item.approvedAmount ? currency.format(item.approvedAmount) : "—"}</strong></span></div>{item.adminNotes && <p><strong>Admin notes:</strong> {item.adminNotes}</p>}</article>)}</div>{open && <Modal title="Submit pay request" eyebrow="Invoice upload required" onClose={() => setOpen(false)}><form className="form-grid" onSubmit={submit}><Field label="Assigned job / scope"><select name="jobId" required><option value="">Select job</option>{jobs.map((job) => <option key={job.id} value={job.id}>{job.title}</option>)}</select></Field><Field label="Amount requested"><input name="amountRequested" type="number" min=".01" step=".01" required /></Field><Field label="Invoice number"><input name="invoiceNumber" required /></Field><Field label="Invoice date"><input name="invoiceDate" type="date" required /></Field><Field label="Invoice file (PDF, image, Word, Excel)"><input name="invoice" type="file" accept=".pdf,.jpg,.jpeg,.png,.doc,.docx,.xls,.xlsx" required /></Field><Field label="Notes"><textarea name="description" rows={4} /></Field><div className="form-actions"><button className="button button-ghost" type="button" onClick={() => setOpen(false)}>Cancel</button><SubmitButton busy={busy}>Submit request</SubmitButton></div></form></Modal>}</>;
}

export function NotificationsPage({ data, mutate }: { data: BootstrapPayload; mutate: Mutation }) { const notices = data.notifications || []; return <><PageHeading eyebrow="Activity inbox" title="Notifications" detail="Unread notifications remain here until you mark them read." actions={<button className="button button-secondary" onClick={() => void mutate("/api/notifications/read", "POST", { all: true })}>Mark all read</button>} /><section className="panel"><div className="compact-list">{notices.map((notice) => <article key={notice.id}><span className="mini-icon"><Bell /></span><span><strong>{notice.title}</strong><small>{notice.detail}</small></span>{!notice.readAt && <button className="button button-small" onClick={() => void mutate("/api/notifications/read", "POST", { ids: [notice.id] })}>Mark read</button>}</article>)}</div>{!notices.length && <EmptyState title="All caught up" detail="Important project activity will appear here." />}</section></> }
