import { useMemo, useState, type FormEvent } from "react";
import { api } from "./api";
import type { BootstrapPayload, ConcreteSupplier } from "./types";

const blank = { company: "", supplierType: "", contactName: "", phone: "", email: "", state: "", notes: "" };
export function SuppliersPage({ data }: { data: BootstrapPayload }) {
  const [suppliers, setSuppliers] = useState<ConcreteSupplier[]>(data.concreteSuppliers || []);
  const [draft, setDraft] = useState(blank); const [search, setSearch] = useState("");
  const shown = useMemo(() => suppliers.filter((supplier) => `${supplier.company} ${supplier.supplierType || ""} ${supplier.state || ""}`.toLowerCase().includes(search.toLowerCase())), [search, suppliers]);
  const save = async (event: FormEvent) => { event.preventDefault(); const saved = await api.mutate<ConcreteSupplier>("/api/yardage/suppliers", "admin", "POST", draft); setSuppliers((current) => [saved, ...current.filter((item) => item.id !== saved.id)]); setDraft(blank); };
  return <><section className="page-heading"><div><p className="eyebrow">Company directory</p><h1>Suppliers</h1><p>Save concrete suppliers and other vendor contacts in one place.</p></div></section><section className="panel"><div className="panel-heading"><div><h2>Add supplier</h2><p>This directory is separate from the Yardage Calculator.</p></div></div><form className="supplier-form" onSubmit={save}><input value={draft.company} onChange={(event) => setDraft({ ...draft, company: event.target.value })} placeholder="Supplier company" required /><input value={draft.supplierType} onChange={(event) => setDraft({ ...draft, supplierType: event.target.value })} placeholder="Supplier type" /><input value={draft.contactName} onChange={(event) => setDraft({ ...draft, contactName: event.target.value })} placeholder="Contact name" /><input value={draft.phone} onChange={(event) => setDraft({ ...draft, phone: event.target.value })} placeholder="Phone" /><input type="email" value={draft.email} onChange={(event) => setDraft({ ...draft, email: event.target.value })} placeholder="Email" /><input value={draft.state} onChange={(event) => setDraft({ ...draft, state: event.target.value.toUpperCase() })} placeholder="State" /><button className="button button-primary">Save supplier</button></form></section><section className="panel"><div className="panel-heading"><div><h2>Supplier directory</h2><p>{suppliers.length} supplier{suppliers.length === 1 ? "" : "s"} saved.</p></div></div><div className="supplier-filter"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search suppliers" /></div><div className="supplier-list">{shown.map((supplier) => <div key={supplier.id}><strong>{supplier.company}</strong><span className="supplier-tags">{supplier.state && <b>{supplier.state}</b>}{supplier.supplierType && <b>{supplier.supplierType}</b>}</span><span>{[supplier.contactName, supplier.phone, supplier.email].filter(Boolean).join(" · ") || "No contact details"}</span></div>)}{!shown.length && <p className="empty-cell">No suppliers match this search.</p>}</div></section></>;
}
